name: Linter

on: push

jobs:
    super-lin:
        name: Lint Code
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4

            -   name: Run Linter
                uses: super-linter/super-linter@v8.0.0
                env:
                    DEFAULT_BRANCH: main
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
